version: "3.8"

services:
  app:
    image: sliderpilerdotcom:1.6.6
    build: 
      context: .
    ports:
      - "80:80"
    command: node app.js
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production