version: "3.8"

services:
  app:
    image: superklok/sliderpilerdotcom:2.17.1
    build: 
      context: .
      target: prod
    ports:
      - "80:80"
    command: serve -s build -p 80
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production